travis:
  secure:
    BINSTAR_TOKEN: WxgjB0b3AgobnzLoBcW9VPcqzzgYveR/k2CztKq61iVjtb3LgAG74Mfqb9cuBgoE/EqpCAjiEQ3PwHTOn5Z4cuMC8Q0MTaIjMZfnHpL1C4rCvGPPYi983kbwi4HQQl+e2ldEvVezlj+E2UfzH88xkS8DPPtWl4y7GW0eHrC7x6yQEdeX0OSa/F855RT1y5+O9YF2VFKeZ1OIZ9tJTO0AB+Jmr4vPJuda2nC7rczAKFPazzX8XihLdhwM+SZcKC0acm8V1SYYY7PpNhkOLE9M0zlvi4Gxep0hxTDzb30VnMqsM109hf6d9UT66VOD8bw0CGQHB69iNoAb202d9uv9n8I3wH7MSkZE+5p/ASr3MEmeBw6sTeqjnuRn8SEU+PccObchdSQIqdHFh27yV8Uqod3DYxIpL5icnEgEvfzrb7NHrPEYOtGK8UWJE+yMzNevNgsAykVXlV6zcGCF5eyfCX+bU4atGki7qHXtQ1UUnGGzn0qlSKP1Gzu7tfEuMjKLlvnblSjyIf+a0+32a0SgmMPx5+khlpcl2cY0QtZ8URgGklp6Vz/rKG03pufjQ8Q/oDuKzgTTjHbx/DSRs4otUM/kj+YLOCT6sZJ6XQu9pFpKROS1PUg5zYGqyKo1oam6s2jG+qAtUREjgA985hoWH/mfzm8OOHq+lNmU+00/X5o=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
